[package]
name = "spinners-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.73"
cxx-build = "1.0.67"

[dependencies]
cty = "0.2.2"
cxx = "1.0.67"
lazy_static = "1.4.0"
maplit = "1.0.2"
